// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { readLegacyAuthValue } from '@/lib/legacySessionStorage';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

const getLegacySessionHeaders = () => {
  if (typeof window === "undefined") {
    return {};
  }

  const gestorId = readLegacyAuthValue("vcd_gestor_id");
  const sessionId = readLegacyAuthValue("vcd_session_id");

  if (!gestorId || !sessionId) {
    return {};
  }

  return {
    "x-vurp-gestor-id": gestorId,
    "x-vurp-session-id": sessionId,
  };
};

const legacyAwareFetch: typeof fetch = (input, init) => {
  const headers = new Headers(init?.headers);

  Object.entries(getLegacySessionHeaders()).forEach(([key, value]) => {
    headers.set(key, value);
  });

  return fetch(input, {
    ...init,
    headers,
  });
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  global: {
    fetch: legacyAwareFetch,
  },
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
